export const ejemplo1 = [
    {
        nombre: "Carlos Pintos",
        titulo: "Ayer por la Noche",
        img: "https://www.clipartmax.com/png/full/270-2707465_vinilo-pixerstick-fondo-del-espacio-abstracto-sol-negro-euclidean-vector.png",
        contenido: "hola mundo, este es mi primer contenido, y mi primer post",
        fecha: "01/01/2001",
        id: "001",
    },
    {
        nombre: "Cristian Farias",
        titulo: "Ayer por la Noche",
        img: "https://cdn.pixabay.com/photo/2018/08/14/13/23/ocean-3605547_1280.jpg",
        contenido: "hola mundo, este es mi primer contenido, y mi primer post",
        fecha: "01/01/2001",
        id: "002",
    },
    {
        nombre: "Pepe Artigas",
        titulo: "Ayer por la Noche",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTOChtnRD0ov0PsZGWP-jDgkPf-8Z4nnGTLvQ&usqp=CAU",
        contenido: "hola mundo, este es mi primer contenido, y mi primer post",
        fecha: "01/01/2001",
        id: "003",
    },
    {
        nombre: "El Tuto",
        titulo: "Ayer por la Noche",
        img: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRJSbmSjYDqgI9j2a2ragEB15meLSOwwOGxKA&usqp=CAU",
        contenido: "hola mundo, este es mi primer contenido, y mi primer post",
        fecha: "01/01/2001",
        id: "004",
    },
    {
        nombre: "El Carlitos",
        titulo: "Ayer por la Noche",
        img: "https://www.clipartmax.com/png/full/270-2707465_vinilo-pixerstick-fondo-del-espacio-abstracto-sol-negro-euclidean-vector.png",
        contenido: "hola mundo, este es mi primer contenido, y mi primer post",
        fecha: "01/01/2001",
        id: "005",
    },
    {
        nombre: "Pepe Artigas",
        titulo: "Ayer por la Noche",
        img: "https://www.clipartmax.com/png/full/270-2707465_vinilo-pixerstick-fondo-del-espacio-abstracto-sol-negro-euclidean-vector.png",
        contenido: "hola mundo, este es mi primer contenido, y mi primer post",
        fecha: "01/01/2001",
        id: "006",
    },
    {
        nombre: "El Tuto",
        titulo: "Ayer por la Noche",
        img: "https://www.clipartmax.com/png/full/270-2707465_vinilo-pixerstick-fondo-del-espacio-abstracto-sol-negro-euclidean-vector.png",
        contenido: "hola mundo, este es mi primer contenido, y mi primer post",
        fecha: "01/01/2001",
        id: "007",
    },
    {
        nombre: "El Carlitos",
        titulo: "Ayer por la Noche",
        img: "https://www.clipartmax.com/png/full/270-2707465_vinilo-pixerstick-fondo-del-espacio-abstracto-sol-negro-euclidean-vector.png",
        contenido: "hola mundo, este es mi primer contenido, y mi primer post",
        fecha: "01/01/2001",
        id: "008",
    },
]